<?php

/**
 * Implements hook_views_api().
 */
/*
function tc_favorite_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'tc_favorite') . '/views',
  );
}
*/

/**
 * Implements hook_menu().
 */
function tc_favorite_menu() {
  $items = array();

  $items['collegesearch/favorite/%'] = array(
    'title' => 'Favorite',
    'page callback' => '_tc_favorite_favorite',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['collegesearch/favorite/remove/%'] = array(
    'title' => 'Remove Favorite',
    'page callback' => '_tc_favorite_favorite_remove',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['collegesearch/favorites/my'] = array(
    'title' => 'See Favorites',
    'page callback' => '_tc_favorite_favorites_my',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Custom callback function for search result "favorite" functionality.
 */
function _tc_favorite_favorite($nid) {
  // Keep things safe.
  $nid = check_plain($nid);
  if (!intval($nid)) {
    drupal_goto('<front>');
  };

  // Get existing favorites.
  $favorites = array();
  if (isset($_SESSION['tc_favorite'])) {
    $favorites = unserialize($_SESSION['tc_favorite']);
  }

  // If the $nid isn't already a favorite, add it.
  if (!array_key_exists($nid, $favorites)) {
    $node = node_load($nid);
    $favorites[$nid] = $node->title;
  }

  // Save back to the session.
  $_SESSION['tc_favorite'] = serialize($favorites);

  return drupal_goto(drupal_get_destination());
}

/**
 * Custom callback function for search result "remove favorite" functionality.
 */
function _tc_favorite_favorite_remove($nid) {
  // Keep things safe.
  $nid = check_plain($nid);
  if (!intval($nid)) {
    drupal_goto('<front>');
  };

  // Get existing favorites.
  $favorites = array();
  if (isset($_SESSION['tc_favorite'])) {
    $favorites = unserialize($_SESSION['tc_favorite']);
  }

  // Remove the favorite.
  unset($favorites[$nid]);

  // Save back to the session.
  $_SESSION['tc_favorite'] = serialize($favorites);

  return drupal_goto(drupal_get_destination());
}

/**
 * Custom callback function for redirect the user to the view showing their favorites.
 */
function _tc_favorite_favorites_my() {
  $favorites_array = array();
  if (isset($_SESSION['tc_favorite'])) {
    $favorites_array = unserialize($_SESSION['tc_favorite']);
  }

  $favorites_string = '';
  if (isset($_SESSION['tc_favorite'])) {
    $favorites_string = implode('+', array_keys($favorites_array));
  }
  $favorites_link = $base_url . '/search/favorites/' . $favorites_string;

  return drupal_goto($favorites_link);
}

/**
 * Custom function to see if a node is a favorite.
 */
function _tc_favorite_is_favorite($nid) {
  // Get existing favorites.
  $favorites = array();
  if (isset($_SESSION['tc_favorite'])) {
    $favorites = unserialize($_SESSION['tc_favorite']);
  }
  return in_array($nid, array_keys($favorites));
}

/**
 * Implements hook_block_info().
 */
function tc_favorite_block_info() {
  $blocks['tc_favorite_favorites'] = array(
    'info' => t('ThinkCollege - User search results favorites'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tc_favorite_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'tc_favorite_favorites':
      $block['subject'] = t('Saved');
      $favorites_block_vars = _tc_favorite_favorites_block();
      $block['content'] = theme('block__tc_favorite__favorites', $favorites_block_vars);
      break;
  }
  return $block;
}

/**
 * Custom function for the "Saved" block's contents.
 */
function _tc_favorite_favorites_block() {
  $result = array();
  if (isset($_SESSION['tc_favorite'])) {
    $emailform = drupal_get_form('_tc_favorite_email_form');
    $favorites = unserialize($_SESSION['tc_favorite']);

    $result = array(
      'template' => 'block__tc_favorite__favorites',
      'favorites' => $favorites,
      'emailform' => $emailform,
    );
  }
  return $result;
}

/**
 * Implements hook_theme().
 */
function tc_favorite_theme($existing, $type, $theme, $path) {
  return array(
    // Main Favorites (Saved) block.
    'block__tc_favorite__favorites' => array(
      'template' => 'block--tc-favorite--favorites',
      'path' => drupal_get_path('module', 'tc_favorite') . '/templates',
      'variables' => array(
        'favorites' => null,
        'emailform' => null,
      ),
    ),

    // Saved button.
    'tc_favorite_button' => array(
      'variables' => array(
        'nid' => null,
        'size' => null,
      ),
    ),
  );
}

/**
 * Custom callback returns email favorites form.
 */
function _tc_favorite_email_form() {
  $form = array();

  $form['tc_favorite_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email address'),
    '#size' => 60,
    '#description' => t('Enter the email address to which these programs will be sent to.'),
  );

  $form['tc_favorite_email_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}

/**
 * Custom callback returns email favorites form validation.
 */
function _tc_favorite_email_form_validate($form, &$form_state) {
  if (!valid_email_address($form_state['values']['tc_favorite_email'])) {
    form_set_error('tc_favorite_email', t('Please enter a valid email address'));
  }
}

/**
 * Custom callback returns email favorites form submit.
 */
function _tc_favorite_email_form_submit($form, &$form_state) {
  $params = array();
  _tc_favorite_email_send($form_state['values']['tc_favorite_email'], $params);
}


/**
 * Implements hook_mail().
 */
function tc_favorite_mail($key, &$message, $params) {
  global $base_url;

  switch ($key) {
    case 'tc_email_favorites':
      // Get the list of favorite Nids.
      $favorites_string = '';
      if (isset($_SESSION['tc_favorite'])) {
        $favorites_array = unserialize($_SESSION['tc_favorite']);
        $favorites_string = implode('+', array_keys($favorites_array));
      }

      $favorites_link = $base_url . '/search/favorites/' . $favorites_string;
      $params['message'] = 'Thanks for using Think College Search to find college programs for students with intellectual disabilities. To see the full list of all the programs you saved, click this link: ' . $favorites_link . '. If you have general questions, or issues with the Think College Search feature, contact us at thinkcollegeTA@gmail.com. For specific questions about a college’s program, contact the program directly.

Best of luck with your search.

Cate Weir
Program Director
Think College Institute for Community Inclusion
School for Global Inclusion and Social Development
University of Massachusetts
Boston
603-848-4901
www.thinkcollege.net';

      $message['subject'] = t('Your favorites from Think College Search');
      $message['body'][] = check_plain($params['message']);
      break;
  }
}

/**
 * Sends an e-mail.
 */
function _tc_favorite_email_send($email_address, $params) {
  // All system mails need to specify the module and template key (mirrored from
  // hook_mail()) that the message they want to send comes from.
  $module = 'tc_favorite';
  $key = 'tc_email_favorites';

  // Specify 'to' and 'from' addresses.
  $to = $email_address;
  $from = variable_get('site_mail', 'admin@example.com');
  $language = language_default();
  $result = drupal_mail($module, $key, $to, $language, $params, $from);
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

}

function theme_tc_favorite_button($variables) {
  $nid = (int)check_plain($variables['nid']);
  if (!$nid) {
    return '';
  }
  if (isset($variables['size'])) {
    $size = $variables['size'];
  }
  else {
    $size = 'xs';
  }
  if (isset($variables['type'])) {
    $type = $variables['type'];
  }
  else {
    $type = 'default';
  }

  if (_tc_favorite_is_favorite($nid)) {
    return '<a href="/collegesearch/favorite/remove/' . $nid . '?destination=' . current_path() . '"type="button" class="btn btn-success btn-' . $size . '"><i class="fa fa-heart" aria-hidden="true"></i> Saved</a>';
  }
  else {
    return '<a href="/collegesearch/favorite/' . $nid . '?destination=' . current_path() . '"type="button" class="btn btn-' . $type . ' btn-' . $size . '"><i class="fa fa-heart" aria-hidden="true"></i> Save</a>';
  }

}
