<?php
// Plugin definition
$plugin = array(
  'title' => t('Think College Dallas'),
  'icon' => 'tc-dallas.png',
  'category' => t('ThinkCollege'),
  'theme' => 'tc_dallas',
  //'css' => 'tc-multipass.css',
  //'admin css' => $bootstrap_css,
  'regions' => array(


    'row1left' => t('Row 1, left'),
    'row1right' => t('Row 1, right'),
    'row2' => t('Row 2'),
    'row3left' => t('Row 3, left'),
    'row3right' => t('Row 3, right'),
    'row4' => t('Row 4'),
    'row5left' => t('Row 5, left'),
    'row5right' => t('Row 5, right'),
    'row6' => t('Row 6'),
  ),
);
