<?php

function admin_css_preprocess_html(&$variables) {
// Add conditional stylesheets for admin pages on admin theme.
  global $theme;
  if ($theme == 'shiny') {
    drupal_add_css(drupal_get_path('module', 'admin_css') . '/css/admin_css.css', array('weight' => CSS_THEME));
    drupal_add_js(drupal_get_path('module', 'admin_css') . '/js/admin_css.js');
  }
}

function admin_css_form_alter(&$form, &$form_state, $form_id) {
  if (path_is_admin(current_path())) {
    $form['resource_node_form']['#attached']['js'][] =
      drupal_get_path('module', 'admin_css') . '/js/admin_css.js';
    $form['resource_node_form']['#attached']['js'][] =
      drupal_get_path('module', 'admin_css') . '/js/jquery.matchHeight.js';
  }
}
/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function admin_css_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    
    $settings['"extraAllowedContent'] = array('div[*];span[*];p[*];img[*];aside[*];button[*];li[*];ol[*];ul[*];nav[*];header[*];footer[*];section[*];form[*];object[*];embed[*];h1[*];h2[*];h3[*];h4[*];');
    
  }
}