<?php

function programnodeform_permission() {
  return array(
    'programnodeform module' => array(
      'title' => t('Survey node form permission'),
  ));
}

function programnodeform_menu() {
  $items = array();
  $items['admin/settings/programnodeform'] = array(
  'title' => 'Survey node form module settings',
  'description' => 'Survey node form module settings',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('programnodeform_admin'),
  'access arguments' => array('administer programnodeform settings'),
  'type' => MENU_NORMAL_ITEM,
 );
  return $items;
}

function programnodeform_query_alter($query) {
  if ($query->hasTag('efq_debug') && module_exists('devel')) {
    dpm((string) $query);
    dpm($query->arguments());
  }
}





function programnodeform_preprocess_node(&$vars){
  global $nid;
    if (arg(0) == 'node' && is_numeric(arg(1)))   $nid = arg(1);



}







function programnodeform_profile_form_submit($form, &$form_state)
{
  $form_state['redirect'] = 'home';
}

function programnodeform_form_alter(&$form, &$form_state, $form_id) {
global $nid;
  if (arg(0) == 'node' && is_numeric(arg(1)))   $nid = arg(1);

global $theme;


if($theme == 'thinkcollege_boot') {
  $form['#prefix']= "";
$form['actions']['submit']['#attributes']['class'][] = 'btn-success';
// $form['actions']['submit']['#submit'][] = 'programnodeform_node_form_redirect';
}






if ($form_id == 'program_record_node_form') {
$url = drupal_get_query_parameters();

$form['actions']['submit']['#attributes']['class'][] = 'btn-success';

if($form_id == 'program_record_node_form') {
// $form_state['no_cache'] = TRUE;
  }
  if($theme == 'thinkcollege_boot'){
    $form['revision_information']['#access'] = false;
    $form['#attached']['js'][]= drupal_get_path('theme', 'bootstrap') . '/js/misc/_vertical-tabs.js'; }
    if($form_id == 'program_record_node_form' && $theme == 'thinkcollege_boot') {$form['#attached']['js'][]= drupal_get_path('module', 'programnodeform') . '/js/programnodeform.js';
    $form['#attached']['css'][]= drupal_get_path('module', 'programnodeform') . '/css/programnodeform.css';
    $form['#attached']['css'][]= drupal_get_path('module', 'programnodeform') . '/css/progrecordfront.css';
if($form['nid']['#value']) {

// Form stays in edit mode on submit
         //$form['actions']['submit']['#submit'][] = '_redirect_to_edit';
         $form['#action'] = '?destination=node/' . $form['nid']['#value'] . '/edit';
       }
     }

  if (!path_is_admin(current_path())) {

  //  drupal_add_js(array('programnodeform' => array('mdmin' => $mdminimum)), array('type' => 'setting'));

//drupal_add_js(array('programnodeform' => array('mdmin' => $settings)), 'setting');
   }






// $field_language = $form[$field_name]['und'];
// $max_delta = $form[$field_name][$field_language]['#max_delta'];
 //unset($form[$field_name][$field_language][$max_delta]);

}
}
