<?php

/**
 * @file
 * Custom facets layouts Using Bootstrap for TC
 *
 * Author: Lee Walker
 * lee@codejourneymen.com
 */

/**
 * Implements hook_element_info_alter().
 *
 * Removed "N/A" options from radio buttons.
 */
function tc_facets_element_info_alter(&$type) {
  $type['radios']['#process'][] = '_tc_facets_remove_radio_na';
}

function _tc_facets_remove_radio_na($element) {
  unset($element['#options']['_none']);
  unset($element['_none']);
  return $element;
}

/**
 * Implements hook_form_alter().
 *
 * Set some placeholder text for Solr search box for "College Search".
 */
function tc_facets_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form") {
    if ($form['#id'] == 'views-exposed-form-tc-resource-search-resource-search-text-input') {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Resource or Keyword";
    }
    else {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Program or Keyword";
    }
  }
}

/**
 * Implements HOOK_facet_items_alter().
 *
 * From facetapi_bonus module.
 * Rename facet titles.
 */
function tc_facets_facet_items_alter(&$build, &$settings) {
  if ($settings->facet == "field_prog_which_disabilities") {
    if (array_key_exists('Yes', $build)) {
      $build['Other disabilities']["#markup"] = "Other Disabilities";
    }
  }
  else if ($settings->facet == "tc_financial_aid") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Offers Financial Aid";
    }
  }
  else if ($settings->facet == "tc_housing") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Offers Housing";
    }
  }
  else if ($settings->facet == "tc_tpsid") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Program is a federally funded TPSID program";
    }
  }
  else if ($settings->facet == "field_prog_length_years") {
    if (array_key_exists('Yes', $build)) {
      $build['Varies']["#markup"] = "Varies by student";
    }
  }
  else if ($settings->facet == "field_prog_type_of_school") {
    if (array_key_exists('Yes', $build)) {
      $build['Other']["#markup"] = "Other";
    }
  }
  else if ($settings->facet == "tc_dual_enroll") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Serves Students in High School *";
    }
  }
}

/**
 * Implements hook_facetapi_sort_info().
 *
 * TC facets have some specific sort requirements that don't fit a standard
 * model (alphabetical, numeric etc) so define them here.
 */
function tc_facets_facetapi_sort_info() {
  $sorts = array();

  $sorts['tc_disability_sort'] = array(
    'label' => t('TC:Disability Sort'),
    'callback' => 'tc_facets_facetapi_sort_disability',
    'description' => t('Special sort order for TC Disability facet.'),
    'weight' => -50,
  );

  $sorts['tc_school_type_sort'] = array(
    'label' => t('TC:School Type Sort'),
    'callback' => 'tc_facets_facetapi_sort_school_type',
    'description' => t('Special sort order for TC school type facet.'),
    'weight' => -50,
  );

  return $sorts;
}

/**
 * Sort in specific Disability order.
 *
 * Intellectual
 * Autism
 * Both
 * Other
 */
function tc_facets_facetapi_sort_disability(array $a, array $b) {
  $ac =0;
  $bc = 0;
  if ($a['#indexed_value'] == "Intellectual disability") {
    $ac = 0;
  }
  else if ($a['#indexed_value'] == "Autism") {
    $ac = 1;
  }
  else if ($a['#indexed_value'] == "BOTH intellectual disability and autism") {
    $ac = 3;
  }
  else if ($a['#indexed_value'] == "Other disabilities") {
    $ac = 4;
  }

  if ($b['#indexed_value'] == "Intellectual disability") {
    $bc = 0;
  }
  else if ($b['#indexed_value'] == "Autism") {
    $bc = 1;
  }
  else if ($b['#indexed_value'] == "BOTH intellectual disability and autism") {
    $bc = 3;
  }
  else if ($b['#indexed_value'] == "Other disabilities") {
    $bc = 4;
  }

  if ($ac == $bc) {
    return 0;
  }
  return ($ac < $bc) ? -1 : 1;
}


/**
 * Sort facets in specific School Type order.
 *
 * 2-year community college or junior college
 * 4-year college or university
 * Both
 * Other
 */
function tc_facets_facetapi_sort_school_type(array $a, array $b) {
  $ac =0;
  $bc = 0;
  if ($a['#indexed_value'] == "2-year community college or junior college") {
    $ac = 0;
  }
  else if ($a['#indexed_value'] == "4-year college or university") {
    $ac = 1;
  }
  else if ($a['#indexed_value'] == "Technical or vocational/trade school") {
    $ac = 3;
  }
  else if ($a['#indexed_value'] == "Other") {
    $ac = 4;
  }

  if ($b['#indexed_value'] == "2-year community college or junior college") {
    $bc = 0;
  }
  else if ($b['#indexed_value'] == "4-year college or university") {
    $bc = 1;
  }
  else if ($b['#indexed_value'] == "Technical or vocational/trade school") {
    $bc = 3;
  }
  else if ($b['#indexed_value'] == "Other") {
    $bc = 4;
  }

  if ($ac == $bc) {
    return 0;
  }
  return ($ac < $bc) ? -1 : 1;
}

/**
 * Implements hook_block_info().
 */
function tc_facets_block_info() {
  $blocks = array();

  $blocks['tc_advanced_filters'] = array(
    'info' => t('TC facets: Advanced Filters'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['tc_resource_advanced_filters'] = array(
    'info' => t('TC facets: Resource Advanced Filters'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['tc_program_features'] = array(
    'info' => t('TC facets: Program Features'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_total_program_count'] = array(
    'info' => t('TC facets: Total count of Programs'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_state_program_count_map'] = array(
    'info' => t('TC facets: Count of Programs per state map'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tc_facets_block_view($delta = '') {
  global $base_url;
  $block = array();

  switch ($delta) {
    case 'tc_advanced_filters':
      $variables['label'] = 'Advanced Filter Label';
      $block['subject'] = t('Advanced Filters');
      $block['content'] = theme('tc_advanced_filters', $variables);
      break;

    case 'tc_resource_advanced_filters':
      $variables['label'] = 'Resource Advanced Filter Label';
      $block['subject'] = t('Resource Advanced Filters');
      $block['content'] = theme('tc_resource_advanced_filters', $variables);
      break;

    case 'tc_program_features':
      $variables['label'] = 'Program Features Label';
      $block['subject'] = t('Program Features Filters');
      $block['content'] = theme('tc_program_features', $variables);
    break;

    case 'tc_total_program_count':
      $variables['label'] = 'Total Programs Available';
      $variables['count'] = variable_get('tc_facets_total_programs', 0);
      $block['subject'] = t('Total Programs Available');
      $block['content'] = theme('tc_total_program_count', $variables);
      break;

    case 'tc_state_program_count_map':
      $variables['label'] = 'Total Programs Available';
      $variables['states'] = unserialize(variable_get('tc_facets_states_count', 0));
      $variables['base_url'] = $base_url;
      $block['subject'] = t('State Programs Available');
      $block['content'] = theme('tc_state_program_count_map', $variables);
      break;

  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function tc_facets_theme($existing, $type, $theme, $path) {
  $return = array(

    'tc_advanced_filters' => array(
      'variables' => array( ),
      'template' => 'templates/tc_advanced_filters'
    ),

    'tc_resource_advanced_filters' => array(
      'variables' => array( ),
      'template' => 'templates/tc_resource_advanced_filters'
    ),

    'tc_program_features' => array(
      'variables' => array( ),
      'template' => 'templates/tc_program_features'
    ),

    'tc_total_program_count' => array(
      'variables' => array( ),
      'template' => 'templates/tc_total_program_count'
    ),

    'tc_state_program_count_map' => array(
      'variables' => array( ),
      'template' => 'templates/tc_state_program_count_map'
    ),

  );

  return $return;
}

/**
 * Get a facet loadout for a search in code.
 * This is used for library page to show facet counts on images.
 *
 * @param null $search_term
 * @return array
 */
function _tc_facets_get_facet_info_from_search($search_term=NULL) {
  $solr_info = _tc_facets_get_solr_connection('dev_solr_server');
  $my_opts = unserialize($solr_info->options);

  $options = array(
    'scheme' => $my_opts['scheme'],
    'host' => $my_opts['host'],
    'port' => $my_opts['port'],
    'path' => $my_opts['path'],
    'http_user' => $my_opts['http_user'],
    'http_pass' => $my_opts['http_pass'],
  );

  $searchConn = new SearchApiSolrConnection($options);
  $params = array(
    'start' => 0,
    'rows' => 1,
    'fl' => 'is_nid,tm_title,tm_field_prog_state,ss_tc_state_province',
    'facet' => "true",
    'facet.field' => 'ss_tc_state_province',
  );

  $result = $searchConn->search($search_term, $params);

  $res = array();
  $res['All Content'] = $result->response->numFound;
  $res['state_counts'] = $result->facet_counts->facet_fields->ss_tc_state_province;
  return $res;
}

/**
 * Look at DB to see how we are connected to Solr.
 *
 * @param $solr_index_machine_name machine name of index to use for search.
 * @return mixed
 */
function _tc_facets_get_solr_connection($solr_index_machine_name) {
  $query = "select * from {search_api_server} where machine_name = '".$solr_index_machine_name."'";
  return db_query($query)->fetchObject();
}

/**
 * Load up total program count and facets values for state counts and store in
 * variables table.
 * @return string
 */
function tc_facets_data_update() {
  $results = _tc_facets_get_facet_info_from_search();
  variable_set('tc_facets_total_programs', $results['All Content']);
  variable_set('tc_facets_states_count', serialize($results['state_counts']));
}

/**
 * Implements hook_cron().
 */
function tc_facets_cron() {
  // Update total program count, and count per state.
  tc_facets_data_update();
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * hook_preprocess_html().
 *
 * @param $variables
 */
/*
function tc_facets_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'tc_facets') . "/tc-college-map/css/mapstyle.css");
  drupal_add_js(drupal_get_path('module', 'tc_facets') . "/tc-college-map/js/mapindex.js");
}
*/
