<?php

/**
 * @file
 * Custom facets layouts Using Bootstrap for TC
 *
 * Author: Lee Walker
 * lee@codejourneymen.com
 */

/**
 * Implements hook_element_info_alter().
 *
 * Removed "N/A" options from radio buttons.
 */
function tc_facets_element_info_alter(&$type) {
  $type['radios']['#process'][] = '_tc_facets_remove_radio_na';
}

function _tc_facets_remove_radio_na($element) {
  unset($element['#options']['_none']);
  unset($element['_none']);
  return $element;
}

/**
 * Implements hook_form_alter().
 *
 * Set some placeholder text for Solr search box for "College Search".
 */
function tc_facets_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form") {
    if ($form['#id'] == 'views-exposed-form-tc-resource-search-resource-search-text-input') {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Resource or Keyword";
    }
    else if ($form['#id'] == 'views-exposed-form-tc-general-site-search-tc-general-search-block') {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Search Entire Site";
    }
    else if ($form['#id'] == 'views-exposed-form-tc-solr-college-search-college-search-solr-search-block') {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Program or Keyword";
    }
    else {
      $form['search_api_views_fulltext']['#attributes']['placeholder'] = "Search";
    }
  }
}

/**
 * Implements HOOK_facet_items_alter().
 *
 * From facetapi_bonus module.
 * Rename facet titles.
 */
function tc_facets_facet_items_alter(&$build, &$settings) {
  if ($settings->facet == "field_prog_which_disabilities") {
    if (array_key_exists('Yes', $build)) {
      $build['Other disabilities']["#markup"] = "Other Disabilities";
    }
  }
  else if ($settings->facet == "tc_financial_aid") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Offers Financial Aid";
    }
  }
  else if ($settings->facet == "tc_housing") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Offers Housing";
    }
  }
  else if ($settings->facet == "tc_tpsid") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Program is a federally funded TPSID program";
    }
  }
  else if ($settings->facet == "field_prog_length_years") {
    if (array_key_exists('Yes', $build)) {
      $build['Varies']["#markup"] = "Varies by student";
    }
  }
  else if ($settings->facet == "field_prog_type_of_school") {
    if (array_key_exists('Yes', $build)) {
      $build['Other']["#markup"] = "Other";
    }
  }
  else if ($settings->facet == "tc_dual_enroll") {
    if (array_key_exists('Yes', $build)) {
      $build['Yes']["#markup"] = "Serves Students in High School *";
    }
  }
}

/**
 * Implements hook_facetapi_sort_info().
 *
 * TC facets have some specific sort requirements that don't fit a standard
 * model (alphabetical, numeric etc) so define them here.
 */
function tc_facets_facetapi_sort_info() {
  $sorts = array();

  $sorts['tc_disability_sort'] = array(
    'label' => t('TC:Disability Sort'),
    'callback' => 'tc_facets_facetapi_sort_disability',
    'description' => t('Special sort order for TC Disability facet.'),
    'weight' => -50,
  );

  $sorts['tc_school_type_sort'] = array(
    'label' => t('TC:School Type Sort'),
    'callback' => 'tc_facets_facetapi_sort_school_type',
    'description' => t('Special sort order for TC school type facet.'),
    'weight' => -50,
  );

  return $sorts;
}

/**
 * Sort in specific Disability order.
 *
 * Intellectual
 * Autism
 * Both
 * Other
 */
function tc_facets_facetapi_sort_disability(array $a, array $b) {
  $ac =0;
  $bc = 0;
  if ($a['#indexed_value'] == "Intellectual disability") {
    $ac = 0;
  }
  else if ($a['#indexed_value'] == "Autism") {
    $ac = 1;
  }
  else if ($a['#indexed_value'] == "BOTH intellectual disability and autism") {
    $ac = 3;
  }
  else if ($a['#indexed_value'] == "Other disabilities") {
    $ac = 4;
  }

  if ($b['#indexed_value'] == "Intellectual disability") {
    $bc = 0;
  }
  else if ($b['#indexed_value'] == "Autism") {
    $bc = 1;
  }
  else if ($b['#indexed_value'] == "BOTH intellectual disability and autism") {
    $bc = 3;
  }
  else if ($b['#indexed_value'] == "Other disabilities") {
    $bc = 4;
  }

  if ($ac == $bc) {
    return 0;
  }
  return ($ac < $bc) ? -1 : 1;
}


/**
 * Sort facets in specific School Type order.
 *
 * 2-year community college or junior college
 * 4-year college or university
 * Both
 * Other
 */
function tc_facets_facetapi_sort_school_type(array $a, array $b) {
  $ac =0;
  $bc = 0;
  if ($a['#indexed_value'] == "2-year community college or junior college") {
    $ac = 0;
  }
  else if ($a['#indexed_value'] == "4-year college or university") {
    $ac = 1;
  }
  else if ($a['#indexed_value'] == "Technical or vocational/trade school") {
    $ac = 3;
  }
  else if ($a['#indexed_value'] == "Other") {
    $ac = 4;
  }

  if ($b['#indexed_value'] == "2-year community college or junior college") {
    $bc = 0;
  }
  else if ($b['#indexed_value'] == "4-year college or university") {
    $bc = 1;
  }
  else if ($b['#indexed_value'] == "Technical or vocational/trade school") {
    $bc = 3;
  }
  else if ($b['#indexed_value'] == "Other") {
    $bc = 4;
  }

  if ($ac == $bc) {
    return 0;
  }
  return ($ac < $bc) ? -1 : 1;
}

/**
 * Implements hook_block_info().
 */
function tc_facets_block_info() {
  $blocks = array();

  $blocks['tc_advanced_filters'] = array(
    'info' => t('TC facets: Advanced Filters'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['tc_resource_advanced_filters'] = array(
    'info' => t('TC facets: Resource Advanced Filters'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['tc_program_features'] = array(
    'info' => t('TC facets: Program Features'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_total_program_count'] = array(
    'info' => t('TC facets: Total count of Programs'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_state_program_count_map'] = array(
    'info' => t('TC facets: Count of Programs per state map'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_program_intro_and_map'] = array(
    'info' => t('TC facets: Program intro block with count and clickable map.'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  $blocks['tc_program_intro_and_map_mobile'] = array(
    'info' => t('TC facets: (Mobile) Program intro block with count and clickable map.'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tc_facets_block_view($delta = '') {
  global $base_url;
  $block = array();
  $pth = drupal_get_path('module', 'tc_facets');
  $variables = array('path' => $pth);

  switch ($delta) {
    case 'tc_advanced_filters':
      $variables['label'] = 'Advanced Filter Label';
      $block['subject'] = t('Advanced Filters');
      $block['content'] = theme('tc_advanced_filters', $variables);
      break;

    case 'tc_resource_advanced_filters':
      $variables['label'] = 'Resource Advanced Filter Label';
      $block['subject'] = t('Resource Advanced Filters');
      $block['content'] = theme('tc_resource_advanced_filters', $variables);
      break;

    case 'tc_program_features':
      $variables['label'] = 'Program Features Label';
      $block['subject'] = t('Program Features Filters');
      $block['content'] = theme('tc_program_features', $variables);
    break;

    case 'tc_total_program_count':
      $variables['label'] = 'Total Programs Available';
      $variables['count'] = variable_get('tc_facets_total_programs', 0);
      $block['subject'] = t('Total Programs Available');
      $block['content'] = theme('tc_total_program_count', $variables);
      break;

    case 'tc_state_program_count_map':
      $variables['label'] = 'Total Programs Available';
      $variables['states'] = unserialize(variable_get('tc_facets_states_count', 0));
      $variables['base_url'] = $base_url;
      $block['subject'] = t('State Programs Available');
      $block['content'] = theme('tc_state_program_count_map', $variables);
      break;

    case 'tc_program_intro_and_map':
      $variables['count'] = variable_get('tc_facets_total_programs', 270);
      $variables['states'] = unserialize(variable_get('tc_facets_states_count', 0));
      $variables['base_url'] = $base_url;
      $block['subject'] = t('Intro text total Programs Available, and Map');
      $block['content'] = theme('tc_program_intro_and_map', $variables);
      break;

    case 'tc_program_intro_and_map_mobile':
      $variables['info_img'] = file_create_url($pth . '/images/students-on-computers-300w.jpg');
      $variables['count'] = variable_get('tc_facets_total_programs', 270);
      $variables['base_url'] = $base_url;
      $block['subject'] = t('Intro text total Programs Available, and Map');
      $block['content'] = theme('tc_program_intro_and_map_mobile', $variables);
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function tc_facets_theme($existing, $type, $theme, $path) {
  $return = array(

    'tc_advanced_filters' => array(
      'variables' => array( ),
      'template' => 'templates/tc_advanced_filters'
    ),

    'tc_resource_advanced_filters' => array(
      'variables' => array( ),
      'template' => 'templates/tc_resource_advanced_filters'
    ),

    'tc_program_features' => array(
      'variables' => array( ),
      'template' => 'templates/tc_program_features'
    ),

    'tc_total_program_count' => array(
      'variables' => array( ),
      'template' => 'templates/tc_total_program_count'
    ),

    'tc_state_program_count_map' => array(
      'variables' => array( ),
      'template' => 'templates/tc_state_program_count_map'
    ),

    'tc_program_intro_and_map' => array(
      'variables' => array( ),
      'template' => 'templates/tc_program_intro_and_map'
    ),

    'tc_program_intro_and_map_mobile' => array(
      'variables' => array( ),
      'template' => 'templates/tc_program_intro_and_map_mobile'
    ),

    'tc_option_select_item' => array(
      'variables' => array( ),
      'template' => 'templates/tc_option_select_item'
    ),

  );

  return $return;
}

/**
 * Implements hook_search_api_solr_search_results_alter().
 *
 * We want to cache the total number of records - if there is no filter - ie max number of records.
 * Also cache total number of programs per state.
 * When a search with no filters is ran, these values we need are in that
 * return value - so cache them.
 *
 * @param array $results
 * @param \SearchApiQueryInterface $query
 * @param $response
 */

function tc_facets_search_api_solr_search_results_alter(array &$results, SearchApiQueryInterface $query, $response) {
  if (($_GET['q'] == 'college-search') && (sizeof($_GET) == 1)) {
    variable_set('tc_facets_total_programs', $results['result count']);
    variable_set('tc_facets_states_count', serialize($response->facet_counts->facet_fields->ss_tc_state_province));
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * hook_preprocess_html().
 *
 * @param $variables
 */
function tc_facets_preprocess_html(&$variables) {
  // The clickable map is only on the initial search page. We don't want
  // the javascript to run and not find the ID of a missing Div and error.
  if (current_path() == "college-search") {
    $params = drupal_get_query_parameters();
    if (sizeof($params) == 0) {
      drupal_add_css(drupal_get_path('module', 'tc_facets') . "/tc-college-map/css/mapstyle.css");
      drupal_add_js(drupal_get_path('module', 'tc_facets') . "/tc-college-map/js/mapindex.js");
    }
  }
}
